/**
 * This class is generated by jOOQ
 */
package org.plos.namedentity.persist.db.namedentities.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Globaltypes extends org.jooq.impl.TableImpl<org.plos.namedentity.persist.db.namedentities.tables.records.GlobaltypesRecord> {

	private static final long serialVersionUID = -1201844978;

	/**
	 * The singleton instance of <code>namedEntities.globalTypes</code>
	 */
	public static final org.plos.namedentity.persist.db.namedentities.tables.Globaltypes GLOBALTYPES = new org.plos.namedentity.persist.db.namedentities.tables.Globaltypes();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.plos.namedentity.persist.db.namedentities.tables.records.GlobaltypesRecord> getRecordType() {
		return org.plos.namedentity.persist.db.namedentities.tables.records.GlobaltypesRecord.class;
	}

	/**
	 * The column <code>namedEntities.globalTypes.globalTypeId</code>.
	 */
	public final org.jooq.TableField<org.plos.namedentity.persist.db.namedentities.tables.records.GlobaltypesRecord, java.lang.Integer> GLOBALTYPEID = createField("globalTypeId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>namedEntities.globalTypes.typeId</code>.
	 */
	public final org.jooq.TableField<org.plos.namedentity.persist.db.namedentities.tables.records.GlobaltypesRecord, java.lang.Integer> TYPEID = createField("typeId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>namedEntities.globalTypes.shortDescription</code>.
	 */
	public final org.jooq.TableField<org.plos.namedentity.persist.db.namedentities.tables.records.GlobaltypesRecord, java.lang.String> SHORTDESCRIPTION = createField("shortDescription", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>namedEntities.globalTypes.longDescription</code>.
	 */
	public final org.jooq.TableField<org.plos.namedentity.persist.db.namedentities.tables.records.GlobaltypesRecord, java.lang.String> LONGDESCRIPTION = createField("longDescription", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>namedEntities.globalTypes.typeCode</code>.
	 */
	public final org.jooq.TableField<org.plos.namedentity.persist.db.namedentities.tables.records.GlobaltypesRecord, java.lang.String> TYPECODE = createField("typeCode", org.jooq.impl.SQLDataType.VARCHAR.length(4), this, "");

	/**
	 * The column <code>namedEntities.globalTypes.created</code>.
	 */
	public final org.jooq.TableField<org.plos.namedentity.persist.db.namedentities.tables.records.GlobaltypesRecord, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>namedEntities.globalTypes.lastModified</code>.
	 */
	public final org.jooq.TableField<org.plos.namedentity.persist.db.namedentities.tables.records.GlobaltypesRecord, java.sql.Timestamp> LASTMODIFIED = createField("lastModified", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>namedEntities.globalTypes.createdBy</code>.
	 */
	public final org.jooq.TableField<org.plos.namedentity.persist.db.namedentities.tables.records.GlobaltypesRecord, java.lang.Integer> CREATEDBY = createField("createdBy", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>namedEntities.globalTypes.lastModifiedBy</code>.
	 */
	public final org.jooq.TableField<org.plos.namedentity.persist.db.namedentities.tables.records.GlobaltypesRecord, java.lang.Integer> LASTMODIFIEDBY = createField("lastModifiedBy", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>namedEntities.globalTypes</code> table reference
	 */
	public Globaltypes() {
		this("globalTypes", null);
	}

	/**
	 * Create an aliased <code>namedEntities.globalTypes</code> table reference
	 */
	public Globaltypes(java.lang.String alias) {
		this(alias, org.plos.namedentity.persist.db.namedentities.tables.Globaltypes.GLOBALTYPES);
	}

	private Globaltypes(java.lang.String alias, org.jooq.Table<org.plos.namedentity.persist.db.namedentities.tables.records.GlobaltypesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Globaltypes(java.lang.String alias, org.jooq.Table<org.plos.namedentity.persist.db.namedentities.tables.records.GlobaltypesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.plos.namedentity.persist.db.namedentities.Namedentities.NAMEDENTITIES, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.plos.namedentity.persist.db.namedentities.tables.records.GlobaltypesRecord, java.lang.Integer> getIdentity() {
		return org.plos.namedentity.persist.db.namedentities.Keys.IDENTITY_GLOBALTYPES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.plos.namedentity.persist.db.namedentities.tables.records.GlobaltypesRecord> getPrimaryKey() {
		return org.plos.namedentity.persist.db.namedentities.Keys.KEY_GLOBALTYPES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.plos.namedentity.persist.db.namedentities.tables.records.GlobaltypesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.plos.namedentity.persist.db.namedentities.tables.records.GlobaltypesRecord>>asList(org.plos.namedentity.persist.db.namedentities.Keys.KEY_GLOBALTYPES_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.plos.namedentity.persist.db.namedentities.tables.records.GlobaltypesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.plos.namedentity.persist.db.namedentities.tables.records.GlobaltypesRecord, ?>>asList(org.plos.namedentity.persist.db.namedentities.Keys.GLOBALTYPES_IBFK_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.plos.namedentity.persist.db.namedentities.tables.Globaltypes as(java.lang.String alias) {
		return new org.plos.namedentity.persist.db.namedentities.tables.Globaltypes(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.plos.namedentity.persist.db.namedentities.tables.Globaltypes rename(java.lang.String name) {
		return new org.plos.namedentity.persist.db.namedentities.tables.Globaltypes(name, null);
	}
}
