=begin


OpenAPI spec version: Swagger Server

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require "uri"

module NedClient
  class QueriesApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # Get a list of search alerts by type
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :frequency 
    # @return [Array<Alert>]
    def get_alerts(opts = {})
      data, status_code, headers = get_alerts_with_http_info(opts)
      return data
    end

    # Get a list of search alerts by type
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :frequency 
    # @return [Array<(Array<Alert>, Fixnum, Hash)>] Array<Alert> data, response status code and response headers
    def get_alerts_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: QueriesApi#get_alerts ..."
      end
      
      # resource path
      path = "/queries/alerts".sub('{format}','json')

      # query parameters
      query_params = {}
      query_params[:'frequency'] = opts[:'frequency'] if opts[:'frequency']

      # header parameters
      header_params = {}

      # HTTP header 'Accept' (if needed)
      _header_accept = ['application/json']
      _header_accept_result = @api_client.select_header_accept(_header_accept) and header_params['Accept'] = _header_accept_result

      # HTTP header 'Content-Type'
      _header_content_type = []
      header_params['Content-Type'] = @api_client.select_header_content_type(_header_content_type)

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      
      auth_names = ['basic']
      data, status_code, headers = @api_client.call_api(:GET, path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Array<Alert>')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: QueriesApi#get_alerts\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
