neddb:
    image: percona:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
 
nedsvc:
    build: nedsvc
    volumes:
      - ../src/main/resources:/mysql_schema
    links:
      - neddb:neddb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_NED_USER=ned
      - MYSQL_NED_PASSWORD=ned
      - MYSQL_HOSTNAME=neddb
      - MYSQL_DATABASE=namedEntities

