nedbuilder:
    build: .
    volumes:
      - ../..:/src   # NED source code
      - ../../../named-entity.etl:/etl    # NED ETL source code
      - /root/.m2   # cache maven cache to docker volume for future builds
      - /build      # to serve out the compiled assets once finished
