/**
 * This class is generated by jOOQ
 */
package org.plos.namedentity.persist.db.information_schema;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in information_schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table information_schema.query_statistics
	 */
	public static final org.plos.namedentity.persist.db.information_schema.tables.QueryStatistics QUERY_STATISTICS = org.plos.namedentity.persist.db.information_schema.tables.QueryStatistics.QUERY_STATISTICS;

	/**
	 * The table information_schema.session_state
	 */
	public static final org.plos.namedentity.persist.db.information_schema.tables.SessionState SESSION_STATE = org.plos.namedentity.persist.db.information_schema.tables.SessionState.SESSION_STATE;

	/**
	 * The table information_schema.locks
	 */
	public static final org.plos.namedentity.persist.db.information_schema.tables.Locks LOCKS = org.plos.namedentity.persist.db.information_schema.tables.Locks.LOCKS;

	/**
	 * The table information_schema.sessions
	 */
	public static final org.plos.namedentity.persist.db.information_schema.tables.Sessions SESSIONS = org.plos.namedentity.persist.db.information_schema.tables.Sessions.SESSIONS;

	/**
	 * The table information_schema.triggers
	 */
	public static final org.plos.namedentity.persist.db.information_schema.tables.Triggers TRIGGERS = org.plos.namedentity.persist.db.information_schema.tables.Triggers.TRIGGERS;

	/**
	 * The table information_schema.domains
	 */
	public static final org.plos.namedentity.persist.db.information_schema.tables.Domains DOMAINS = org.plos.namedentity.persist.db.information_schema.tables.Domains.DOMAINS;

	/**
	 * The table information_schema.constants
	 */
	public static final org.plos.namedentity.persist.db.information_schema.tables.Constants CONSTANTS = org.plos.namedentity.persist.db.information_schema.tables.Constants.CONSTANTS;

	/**
	 * The table information_schema.function_columns
	 */
	public static final org.plos.namedentity.persist.db.information_schema.tables.FunctionColumns FUNCTION_COLUMNS = org.plos.namedentity.persist.db.information_schema.tables.FunctionColumns.FUNCTION_COLUMNS;

	/**
	 * The table information_schema.constraints
	 */
	public static final org.plos.namedentity.persist.db.information_schema.tables.Constraints CONSTRAINTS = org.plos.namedentity.persist.db.information_schema.tables.Constraints.CONSTRAINTS;

	/**
	 * The table information_schema.cross_references
	 */
	public static final org.plos.namedentity.persist.db.information_schema.tables.CrossReferences CROSS_REFERENCES = org.plos.namedentity.persist.db.information_schema.tables.CrossReferences.CROSS_REFERENCES;

	/**
	 * The table information_schema.in_doubt
	 */
	public static final org.plos.namedentity.persist.db.information_schema.tables.InDoubt IN_DOUBT = org.plos.namedentity.persist.db.information_schema.tables.InDoubt.IN_DOUBT;

	/**
	 * The table information_schema.views
	 */
	public static final org.plos.namedentity.persist.db.information_schema.tables.Views VIEWS = org.plos.namedentity.persist.db.information_schema.tables.Views.VIEWS;

	/**
	 * The table information_schema.collations
	 */
	public static final org.plos.namedentity.persist.db.information_schema.tables.Collations COLLATIONS = org.plos.namedentity.persist.db.information_schema.tables.Collations.COLLATIONS;

	/**
	 * The table information_schema.column_privileges
	 */
	public static final org.plos.namedentity.persist.db.information_schema.tables.ColumnPrivileges COLUMN_PRIVILEGES = org.plos.namedentity.persist.db.information_schema.tables.ColumnPrivileges.COLUMN_PRIVILEGES;

	/**
	 * The table information_schema.table_privileges
	 */
	public static final org.plos.namedentity.persist.db.information_schema.tables.TablePrivileges TABLE_PRIVILEGES = org.plos.namedentity.persist.db.information_schema.tables.TablePrivileges.TABLE_PRIVILEGES;

	/**
	 * The table information_schema.schemata
	 */
	public static final org.plos.namedentity.persist.db.information_schema.tables.Schemata SCHEMATA = org.plos.namedentity.persist.db.information_schema.tables.Schemata.SCHEMATA;

	/**
	 * The table information_schema.function_aliases
	 */
	public static final org.plos.namedentity.persist.db.information_schema.tables.FunctionAliases FUNCTION_ALIASES = org.plos.namedentity.persist.db.information_schema.tables.FunctionAliases.FUNCTION_ALIASES;

	/**
	 * The table information_schema.rights
	 */
	public static final org.plos.namedentity.persist.db.information_schema.tables.Rights RIGHTS = org.plos.namedentity.persist.db.information_schema.tables.Rights.RIGHTS;

	/**
	 * The table information_schema.roles
	 */
	public static final org.plos.namedentity.persist.db.information_schema.tables.Roles ROLES = org.plos.namedentity.persist.db.information_schema.tables.Roles.ROLES;

	/**
	 * The table information_schema.users
	 */
	public static final org.plos.namedentity.persist.db.information_schema.tables.Users USERS = org.plos.namedentity.persist.db.information_schema.tables.Users.USERS;

	/**
	 * The table information_schema.sequences
	 */
	public static final org.plos.namedentity.persist.db.information_schema.tables.Sequences SEQUENCES = org.plos.namedentity.persist.db.information_schema.tables.Sequences.SEQUENCES;

	/**
	 * The table information_schema.help
	 */
	public static final org.plos.namedentity.persist.db.information_schema.tables.Help HELP = org.plos.namedentity.persist.db.information_schema.tables.Help.HELP;

	/**
	 * The table information_schema.settings
	 */
	public static final org.plos.namedentity.persist.db.information_schema.tables.Settings SETTINGS = org.plos.namedentity.persist.db.information_schema.tables.Settings.SETTINGS;

	/**
	 * The table information_schema.catalogs
	 */
	public static final org.plos.namedentity.persist.db.information_schema.tables.Catalogs CATALOGS = org.plos.namedentity.persist.db.information_schema.tables.Catalogs.CATALOGS;

	/**
	 * The table information_schema.type_info
	 */
	public static final org.plos.namedentity.persist.db.information_schema.tables.TypeInfo TYPE_INFO = org.plos.namedentity.persist.db.information_schema.tables.TypeInfo.TYPE_INFO;

	/**
	 * The table information_schema.table_types
	 */
	public static final org.plos.namedentity.persist.db.information_schema.tables.TableTypes TABLE_TYPES = org.plos.namedentity.persist.db.information_schema.tables.TableTypes.TABLE_TYPES;

	/**
	 * The table information_schema.indexes
	 */
	public static final org.plos.namedentity.persist.db.information_schema.tables.Indexes INDEXES = org.plos.namedentity.persist.db.information_schema.tables.Indexes.INDEXES;

	/**
	 * The table information_schema.columns
	 */
	public static final org.plos.namedentity.persist.db.information_schema.tables.Columns COLUMNS = org.plos.namedentity.persist.db.information_schema.tables.Columns.COLUMNS;

	/**
	 * The table information_schema.tables
	 */
	public static final org.plos.namedentity.persist.db.information_schema.tables.Tables TABLES = org.plos.namedentity.persist.db.information_schema.tables.Tables.TABLES;
}
