neddb:
    image: percona:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root

nedapi:
    build: .
    links:
      - neddb:neddb
#    ports:
#      - "8080:8080"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_NED_USER=ned
      - MYSQL_NED_PASSWORD=ned
      - MYSQL_HOSTNAME=neddb
      - MYSQL_DATABASE=namedEntities
