#!/usr/bin/env bash

#set -x
set -e

case "$1" in
  configure|reconfigure)

    . /usr/share/debconf/confmodule

#    TODO: check first to see that the DB is up before entering credentials?

    INPUT="db_input high [[artifactId]]"

    $INPUT/ned_db_host || true
    $INPUT/ned_db_user || true
    $INPUT/ned_db_password || true
    $INPUT/ringgold_db_host || true
    $INPUT/ringgold_db_user || true
    $INPUT/ringgold_db_password || true
    $INPUT/ringgold_import_dir || true
    $INPUT/tomcat_admin_user || true
    $INPUT/tomcat_admin_password || true
    $INPUT/http_port || true
    $INPUT/control_port || true

    db_go || true

  ;;

  abort-upgrade)
  ;;

  *)
      echo "config called with unknown argument \`$1'" >&2
      exit 1
  ;;
esac
