#!/usr/bin/env bash

#set -x
set -o errexit


function process_env_template {
	CONTEXT_TEMPALTE=$1

  ls -lh $CONTEXT_TEMPALTE

	echo "Processing template $CONTEXT_TEMPALTE"

  eval "cat <<EOF
$(<$CONTEXT_TEMPALTE)
EOF
" > $CONTEXT_TEMPALTE
}

. /usr/share/debconf/confmodule

# HACK: until I can figure out how to do this from jdeb
chmod +x /opt/plos/ned/bin/*.sh

# Fetching configuration from debconf

db_get [[artifactId]]/ned_db_user
export NED_DB_USER=$RET

db_get [[artifactId]]/ned_db_password
export NED_DB_PASSWORD=$RET

db_get [[artifactId]]/ned_db_host
export NED_DB_HOST=$RET

db_get [[artifactId]]/ringgold_db_user
export RINGGOLD_DB_USER=$RET

db_get [[artifactId]]/ringgold_db_password
export RINGGOLD_DB_PASSWORD=$RET

db_get [[artifactId]]/ringgold_db_host
export RINGGOLD_DB_HOST=$RET

db_get [[artifactId]]/ringgold_import_dir
export RINGGOLD_DIR=$RET

# generate the context.xml
process_env_template /opt/plos/ned/conf/context.xml
cat /opt/plos/ned/conf/context.xml

# run the migrations and import ringgold
export MIGRATIONS_DIR=/opt/plos/ned/migrations
/opt/plos/ned/bin/migrate.sh

# removes the saved values, so they need to be re-entered the next time around
# probably should move this to the postrm or something?
db_purge


## start ned service, if exists.
#if service --status-all 2>&1 | grep -wq 'ned'; then
#  echo 'sudo service ned start'
#  sudo service ned start
#fi
