#!/bin/bash
set -o errexit

echo 'preinst script executing'

# stop ned service, if exists.    
if service --status-all 2>&1 | grep -wq 'ned'; then    
  echo 'sudo service ned stop'
  sudo service ned stop 

  echo 'delete expanded webapp dir (/opt/plos/ned/webapps/v1)'
  rm -rf /opt/plos/ned/webapps/v1
fi
