#!/usr/bin/env bash

#set -x
#set -o errexit

. /usr/share/debconf/confmodule

db_input high [[artifactId]]/ned_db_host || true
db_input high [[artifactId]]/ned_db_user || true
db_input high [[artifactId]]/ned_db_password || true
db_input high [[artifactId]]/ringgold_db_host || true
db_input high [[artifactId]]/ringgold_db_user || true
db_input high [[artifactId]]/ringgold_db_password || true
db_input high [[artifactId]]/ringgold_import_dir || true

db_go || true
