#!/usr/bin/env bash

set -e

case "$1" in
  remove|upgrade|deconfigure)
    [ -f /etc/default/ned ] && . /etc/default/ned
    # Remove auth for tomcat8 to open privileged ports via authbind.
    TOMCAT_UID="$(id -u ned)"
    if [ -f "/etc/authbind/byuid/$TOMCAT_UID" ]; then
      rm -f "/etc/authbind/byuid/$TOMCAT_UID"
    fi
  ;;

  failed-upgrade)
  ;;

  *)
    echo "prerm called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

if [ -x "/etc/init.d/ned" ] || [ -e "/etc/init/ned.conf" ]; then
#	invoke-rc.d ned stop || true
	service ned stop || true
fi
