/**
 * This class is generated by jOOQ
 */
package org.plos.namedentity.persist.db.information_schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Constraints extends org.jooq.impl.TableImpl<org.plos.namedentity.persist.db.information_schema.tables.records.ConstraintsRecord> {

	private static final long serialVersionUID = 814857684;

	/**
	 * The singleton instance of <code>information_schema.constraints</code>
	 */
	public static final org.plos.namedentity.persist.db.information_schema.tables.Constraints CONSTRAINTS = new org.plos.namedentity.persist.db.information_schema.tables.Constraints();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.plos.namedentity.persist.db.information_schema.tables.records.ConstraintsRecord> getRecordType() {
		return org.plos.namedentity.persist.db.information_schema.tables.records.ConstraintsRecord.class;
	}

	/**
	 * The column <code>information_schema.constraints.constraint_catalog</code>.
	 */
	public final org.jooq.TableField<org.plos.namedentity.persist.db.information_schema.tables.records.ConstraintsRecord, java.lang.String> CONSTRAINT_CATALOG = createField("constraint_catalog", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>information_schema.constraints.constraint_schema</code>.
	 */
	public final org.jooq.TableField<org.plos.namedentity.persist.db.information_schema.tables.records.ConstraintsRecord, java.lang.String> CONSTRAINT_SCHEMA = createField("constraint_schema", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>information_schema.constraints.constraint_name</code>.
	 */
	public final org.jooq.TableField<org.plos.namedentity.persist.db.information_schema.tables.records.ConstraintsRecord, java.lang.String> CONSTRAINT_NAME = createField("constraint_name", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>information_schema.constraints.constraint_type</code>.
	 */
	public final org.jooq.TableField<org.plos.namedentity.persist.db.information_schema.tables.records.ConstraintsRecord, java.lang.String> CONSTRAINT_TYPE = createField("constraint_type", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>information_schema.constraints.table_catalog</code>.
	 */
	public final org.jooq.TableField<org.plos.namedentity.persist.db.information_schema.tables.records.ConstraintsRecord, java.lang.String> TABLE_CATALOG = createField("table_catalog", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>information_schema.constraints.table_schema</code>.
	 */
	public final org.jooq.TableField<org.plos.namedentity.persist.db.information_schema.tables.records.ConstraintsRecord, java.lang.String> TABLE_SCHEMA = createField("table_schema", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>information_schema.constraints.table_name</code>.
	 */
	public final org.jooq.TableField<org.plos.namedentity.persist.db.information_schema.tables.records.ConstraintsRecord, java.lang.String> TABLE_NAME = createField("table_name", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>information_schema.constraints.unique_index_name</code>.
	 */
	public final org.jooq.TableField<org.plos.namedentity.persist.db.information_schema.tables.records.ConstraintsRecord, java.lang.String> UNIQUE_INDEX_NAME = createField("unique_index_name", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>information_schema.constraints.check_expression</code>.
	 */
	public final org.jooq.TableField<org.plos.namedentity.persist.db.information_schema.tables.records.ConstraintsRecord, java.lang.String> CHECK_EXPRESSION = createField("check_expression", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>information_schema.constraints.column_list</code>.
	 */
	public final org.jooq.TableField<org.plos.namedentity.persist.db.information_schema.tables.records.ConstraintsRecord, java.lang.String> COLUMN_LIST = createField("column_list", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>information_schema.constraints.remarks</code>.
	 */
	public final org.jooq.TableField<org.plos.namedentity.persist.db.information_schema.tables.records.ConstraintsRecord, java.lang.String> REMARKS = createField("remarks", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>information_schema.constraints.sql</code>.
	 */
	public final org.jooq.TableField<org.plos.namedentity.persist.db.information_schema.tables.records.ConstraintsRecord, java.lang.String> SQL = createField("sql", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>information_schema.constraints.id</code>.
	 */
	public final org.jooq.TableField<org.plos.namedentity.persist.db.information_schema.tables.records.ConstraintsRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>information_schema.constraints</code> table reference
	 */
	public Constraints() {
		this("constraints", null);
	}

	/**
	 * Create an aliased <code>information_schema.constraints</code> table reference
	 */
	public Constraints(java.lang.String alias) {
		this(alias, org.plos.namedentity.persist.db.information_schema.tables.Constraints.CONSTRAINTS);
	}

	private Constraints(java.lang.String alias, org.jooq.Table<org.plos.namedentity.persist.db.information_schema.tables.records.ConstraintsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Constraints(java.lang.String alias, org.jooq.Table<org.plos.namedentity.persist.db.information_schema.tables.records.ConstraintsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.plos.namedentity.persist.db.information_schema.InformationSchema.INFORMATION_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.plos.namedentity.persist.db.information_schema.tables.Constraints as(java.lang.String alias) {
		return new org.plos.namedentity.persist.db.information_schema.tables.Constraints(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.plos.namedentity.persist.db.information_schema.tables.Constraints rename(java.lang.String name) {
		return new org.plos.namedentity.persist.db.information_schema.tables.Constraints(name, null);
	}
}
