/**
 * This class is generated by jOOQ
 */
package org.plos.namedentity.persist.db.information_schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FunctionAliases extends org.jooq.impl.TableImpl<org.plos.namedentity.persist.db.information_schema.tables.records.FunctionAliasesRecord> {

	private static final long serialVersionUID = -855316157;

	/**
	 * The singleton instance of <code>information_schema.function_aliases</code>
	 */
	public static final org.plos.namedentity.persist.db.information_schema.tables.FunctionAliases FUNCTION_ALIASES = new org.plos.namedentity.persist.db.information_schema.tables.FunctionAliases();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.plos.namedentity.persist.db.information_schema.tables.records.FunctionAliasesRecord> getRecordType() {
		return org.plos.namedentity.persist.db.information_schema.tables.records.FunctionAliasesRecord.class;
	}

	/**
	 * The column <code>information_schema.function_aliases.alias_catalog</code>.
	 */
	public final org.jooq.TableField<org.plos.namedentity.persist.db.information_schema.tables.records.FunctionAliasesRecord, java.lang.String> ALIAS_CATALOG = createField("alias_catalog", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>information_schema.function_aliases.alias_schema</code>.
	 */
	public final org.jooq.TableField<org.plos.namedentity.persist.db.information_schema.tables.records.FunctionAliasesRecord, java.lang.String> ALIAS_SCHEMA = createField("alias_schema", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>information_schema.function_aliases.alias_name</code>.
	 */
	public final org.jooq.TableField<org.plos.namedentity.persist.db.information_schema.tables.records.FunctionAliasesRecord, java.lang.String> ALIAS_NAME = createField("alias_name", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>information_schema.function_aliases.java_class</code>.
	 */
	public final org.jooq.TableField<org.plos.namedentity.persist.db.information_schema.tables.records.FunctionAliasesRecord, java.lang.String> JAVA_CLASS = createField("java_class", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>information_schema.function_aliases.java_method</code>.
	 */
	public final org.jooq.TableField<org.plos.namedentity.persist.db.information_schema.tables.records.FunctionAliasesRecord, java.lang.String> JAVA_METHOD = createField("java_method", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>information_schema.function_aliases.data_type</code>.
	 */
	public final org.jooq.TableField<org.plos.namedentity.persist.db.information_schema.tables.records.FunctionAliasesRecord, java.lang.Integer> DATA_TYPE = createField("data_type", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>information_schema.function_aliases.type_name</code>.
	 */
	public final org.jooq.TableField<org.plos.namedentity.persist.db.information_schema.tables.records.FunctionAliasesRecord, java.lang.String> TYPE_NAME = createField("type_name", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>information_schema.function_aliases.column_count</code>.
	 */
	public final org.jooq.TableField<org.plos.namedentity.persist.db.information_schema.tables.records.FunctionAliasesRecord, java.lang.Integer> COLUMN_COUNT = createField("column_count", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>information_schema.function_aliases.returns_result</code>.
	 */
	public final org.jooq.TableField<org.plos.namedentity.persist.db.information_schema.tables.records.FunctionAliasesRecord, java.lang.Short> RETURNS_RESULT = createField("returns_result", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * The column <code>information_schema.function_aliases.remarks</code>.
	 */
	public final org.jooq.TableField<org.plos.namedentity.persist.db.information_schema.tables.records.FunctionAliasesRecord, java.lang.String> REMARKS = createField("remarks", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>information_schema.function_aliases.id</code>.
	 */
	public final org.jooq.TableField<org.plos.namedentity.persist.db.information_schema.tables.records.FunctionAliasesRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>information_schema.function_aliases.source</code>.
	 */
	public final org.jooq.TableField<org.plos.namedentity.persist.db.information_schema.tables.records.FunctionAliasesRecord, java.lang.String> SOURCE = createField("source", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * Create a <code>information_schema.function_aliases</code> table reference
	 */
	public FunctionAliases() {
		this("function_aliases", null);
	}

	/**
	 * Create an aliased <code>information_schema.function_aliases</code> table reference
	 */
	public FunctionAliases(java.lang.String alias) {
		this(alias, org.plos.namedentity.persist.db.information_schema.tables.FunctionAliases.FUNCTION_ALIASES);
	}

	private FunctionAliases(java.lang.String alias, org.jooq.Table<org.plos.namedentity.persist.db.information_schema.tables.records.FunctionAliasesRecord> aliased) {
		this(alias, aliased, null);
	}

	private FunctionAliases(java.lang.String alias, org.jooq.Table<org.plos.namedentity.persist.db.information_schema.tables.records.FunctionAliasesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.plos.namedentity.persist.db.information_schema.InformationSchema.INFORMATION_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.plos.namedentity.persist.db.information_schema.tables.FunctionAliases as(java.lang.String alias) {
		return new org.plos.namedentity.persist.db.information_schema.tables.FunctionAliases(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.plos.namedentity.persist.db.information_schema.tables.FunctionAliases rename(java.lang.String name) {
		return new org.plos.namedentity.persist.db.information_schema.tables.FunctionAliases(name, null);
	}
}
