#!/usr/bin/env bash

# set -x

FLYWAY_DOWNLOAD=https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/4.0.3/flyway-commandline-4.0.3.tar.gz

# change to this directory
DIR="$( dirname "${BASH_SOURCE[0]}" )"

CMD=$DIR/flyway-*/flyway

# use flyway installed on system, or pull one down to use
if type flyway &>/dev/null 2>&1; then
	CMD=flyway
elif ls $DIR/flyway-* &>/dev/null 2>&1; then
	echo
else
	wget -O - $FLYWAY_DOWNLOAD | tar xz -C $DIR
fi

$CMD -v > /dev/null|| (echo "Error: Flyway not found" && exit 2)

$CMD $@

# example use:  ./flyway -url="jdbc:mysql://localhost/namedEntities" -user=name -password=password -locations=filesystem:./migrations migrate
