=begin


OpenAPI spec version: Swagger Server

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'

# Unit tests for NedClient::QueriesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'QueriesApi' do
  before do
    # run before each test
    @instance = NedClient::QueriesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of QueriesApi' do
    it 'should create an instact of QueriesApi' do
      @instance.should be_a(NedClient::QueriesApi)
    end
  end

  # unit tests for get_alerts
  # Get a list of search alerts by type
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :frequency 
  # @return [Array<Alert>]
  describe 'get_alerts test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

end
