=begin


OpenAPI spec version: Swagger Server

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'

# Unit tests for NedClient::ServiceApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ServiceApi' do
  before do
    # run before each test
    @instance = NedClient::ServiceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ServiceApi' do
    it 'should create an instact of ServiceApi' do
      @instance.should be_a(NedClient::ServiceApi)
    end
  end

  # unit tests for config
  # Config info
  # 
  # @param [Hash] opts the optional parameters
  # @return [ConfigInfo]
  describe 'config test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for errorcodes
  # List possible error codes
  # 
  # @param [Hash] opts the optional parameters
  # @return [Array<NedErrorResponse>]
  describe 'errorcodes test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

end
